import streamlit as st
st.write("Hello☺️! This is a helpful daily schedule to help you be more: Fabulously Encouraging, Lovely, Incredible, Careing, Incomprehendibly Trustworthy, Yummilicious!")

st.checkbox("Wake up")
st.checkbox("Shower")
st.checkbox("brush teeth")
st.checkbox("brush hair")
st.checkbox("wash face")
st.checkbox("get dressed")
st.checkbox("iron pants")
st.checkbox("wash laundry")
st.checkbox("make breakfast")
st.checkbox("eat breakfast")
st.checkbox("take out laundry")
st.checkbox("fold laundry")
st.checkbox("put away clothes")
st.checkbox("pack lunch(s)")
st.checkbox("get on shoes")
st.checkbox("tie laces")
st.checkbox("walk out door")
st.checkbox("close door")
st.checkbox("go to work")
st.checkbox("go to school")
st.checkbox("start school")
st.checkbox("come home")
st.checkbox("check checklist")
st.checkbox("do homework")
st.checkbox("jump for joy!")
